### ISSUE TITLE
Menu Screen Bug

### ISSUE THREAD

**Issue by DDShadowRU** [DDCompany/AchievementsAPI_PE#1]
The mod break menu screen in 1.16
![Screenshot_20210916-061857_Horizon.jpg](https://user-images.githubusercontent.com/28687012/133543980-21023eb1-2190-47c6-ad5e-e09d4cfe97d4.jpg)

**Comment by SilentPerl** [comment]
Не работает

**Comment by SilentPerl** [comment]
Работает

**Comment by DDShadowRU** [comment]
🗿
